cairo:
  - 1.14.12
freetype:
  - 2.9.1
glib:
  - 2.63
  #- 2.56
gsl:
  - 2.4
icu:
  - 58.2
jpeg:
  - 9b
krb5:
  - 1.17.1
  #- 1.16.1
libcurl:
  - 7.62.0
libpng:
  - 1.6.37
libssh2:
  - 1.8.2
libtiff:
  - 4.0.10
libxml2:
  - 2.9.9
ncurses:
  - 6.1
pango:
  - 1.42.4
pcre:
  - 8.43
readline:
  - 8.0
  #- 7.0
tk:
  - 8.6.8
xz:
  - 5.2.4
