{% set native = 'm2w64-' if win else '' %}
{% set posix = 'm2-' if win else '' %}
{% set version = '3.5.1' %}

package:
  name: r-base
  version: {{ version }}

source:
  url: https://cran.r-project.org/src/base/R-3/R-{{ version }}.tar.gz
  sha256: 0463bff5eea0f3d93fa071f79c18d0993878fd4f2e18ae6cf22c1639d11457ed
  patches:
    - mac-unicode.patch  # [osx]
    - 0002-Win32-Fix-trio-config-h-include-depth-issue.patch
    - 0003-Win32-Do-not-static-libgcc-link.patch              # This patch is only correct if using MSYS2's tcltk.
    - 0005-Win32-Extend-sqrt-NA_real_-hack-to-all-GCC-versions.patch
    - 0006-Win32-GCC-5.3-Fix-ISNAN-int-emits-UD2-insn.patch
    - 0007-Win32-MSYS2-ENV_CONV_EXCL_R_ARCH.patch
    - 0008-Darwin-set-DYLD_FALLBACK_LIBRARY_PATH.patch
    - 0009-R-3.3.0-Use-AC_SEARCH_LIBS-to-search-for-ncurses.patch
    - 0011-Linux-Do-not-modify-LD_LIBRARY_PATH.patch
    - 0012-macOS-include-cairo_h-not-cairo-xlib_h.patch
    - 0013-javareconf-do-not-fail-on-compile-fail.patch

build:
  number: 1001
  merge_build_host: True   # [win]
  rpaths:
    - lib/R/lib/
    - lib/
  no_link:
    # These files are modified by R CMD javareconf and can
    # point to different Java implementations in each env.
    - lib/R/etc/Makeconf
    - lib/R/etc/ldpaths
    - lib/R/etc/javaconf
    - lib/R/etc/x64/Makeconf
    - lib/R/etc/x64/ldpaths
    - lib/R/etc/x64/javaconf
  detect_binary_files_with_prefix: true

requirements:
  build:
    - posix                    # [win]
    - m2-texinfo-tex           # [win]
    - m2-texinfo               # [win]
    - m2-curl                  # [win]
    - m2-p7zip                 # [win]
    - texlive-core             # [osx]
    - {{posix}}pkg-config
    - {{posix}}autoconf
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}automake          # [not win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - readline                 # [not win]
    - ncurses                  # [not win]
    - jpeg                     # [not win]
    - curl                     # [not win]
    - xz                       # [not win]
    - bzip2                    # [not win]
    - libpng                   # [not win]
    - cairo                    # [not win]
    - libssh2                  # [not win]
    - openssl                  # [not win]
    - krb5                     # [not win]
    - {{native}}bzip2 1.0.*    # [not osx]
    - {{native}}libjpeg-turbo  # [win]
    - {{native}}libiconv       # [win]
    - {{native}}gmp 6.1.*      # [win]
    - {{native}}fftw           # [win]
    - {{native}}xz             # [win]
    - {{native}}mpfr 3.1.*     # [win]
    - {{native}}libsndfile     # [win]
    - {{native}}bwidget        # [win]
    - {{native}}tktable        # [win]
    - {{native}}libpng         # [win]
    - pango                    # [not win]
    - icu                      # [not win]
    - pcre                     # [not win]
    - {{native}}pcre           # [win]
    - {{native}}tk             # [win]
    - tk                       # [not win]
    - zlib                     # [not win]
    - {{native}}zlib           # [win]
    - {{native}}gsl            # [win]
    - gsl                      # [not win]
    - libtiff                  # [not win]
    - {{native}}libtiff        # [win]
    - {{native}}libxml2 2.9.*  # [win]
    - libxml2                  # [not win]
    - xorg-libx11              # [linux]
    - xorg-libxt               # [linux]
    - xorg-libxrender          # [linux]
    - xorg-libxext             # [linux]
    - xorg-libxdmcp            # [linux]


  run:
    - readline                 # [not win]
    - ncurses                  # [not win]
    - jpeg                     # [not win]
    - curl                     # [not win]
    - xz                       # [not win]
    - bzip2                    # [not win]
    - libpng                   # [not win]
    - cairo                    # [not win]
    - libssh2                  # [not win]
    - openssl                  # [not win]
    - krb5                     # [not win]
    - {{native}}bzip2 1.0.*    # [not osx]
    - {{native}}libjpeg-turbo  # [win]
    - {{native}}libiconv       # [win]
    - {{native}}gmp 6.1.*      # [win]
    - {{native}}fftw           # [win]
    - {{native}}xz             # [win]
    - {{native}}mpfr 3.1.*     # [win]
    - {{native}}libsndfile     # [win]
    - {{native}}bwidget        # [win]
    - {{native}}tktable        # [win]
    - {{native}}libpng         # [win]
    - pango                    # [not win]
    - icu                      # [not win]
    - pcre                     # [not win]
    - {{native}}pcre           # [win]
    - {{native}}tk             # [win]
    - tk                       # [not win]
    - zlib                     # [not win]
    - {{native}}zlib           # [win]
    - {{native}}gsl            # [win]
    - gsl                      # [not win]
    - libtiff                  # [not win]
    - {{native}}libtiff        # [win]
    - {{native}}libxml2 2.9.*  # [win]
    - libxml2                  # [not win]
    - xorg-libx11              # [linux]
    - xorg-libxt               # [linux]
    - xorg-libxrender          # [linux]
    - xorg-libxext             # [linux]
    - xorg-libxdmcp            # [linux]

test:
  commands:
    - R -h
    - R --version
    - Rscript --version
    - Rscript -e  'cat("ok\\n")'
    # TODO does not work on windows, because winCairo.dll is missing
    - Rscript test-svg.R       # [not win]
    - open                     # [win]
    # There doesn't seem to be a way to test this one
    # - RSetReg  # [win]
    - Rfe --help               # [win]
    - Rterm --help             # [win]
    - Rterm --version          # [win]
    # Prevent regression mentioned in https://github.com/conda-forge/r-base-feedstock/issues/50
    - Rscript -e "stopifnot(capabilities('jpeg'), TRUE)"
    - Rscript -e "stopifnot(capabilities('png'), TRUE)"
  files:
    - test-svg.R


about:
  home: http://www.r-project.org/
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'R is a free software environment for statistical computing and graphics.'

extra:
  recipe-maintainers:
    - johanneskoester
    - ocefpaf
    - sodre
    - bgruening
    - isuruf
