{% set native = 'm2w64-' if win else '' %}
{% set posix = 'm2-' if win else '' %}
{% set version= '3.4.3' %}

package:
  name: r-base
  version: {{ version }}

source:
  url: https://cran.r-project.org/src/base/R-3/R-{{ version }}.tar.gz
  sha256: 7a3cb831de5b4151e1f890113ed207527b7d4b16df9ec6b35e0964170007f426
  patches:
    - mac-unicode.patch  # [osx]
    - 0002-Win32-Fix-trio-config-h-include-depth-issue.patch
    - 0003-Win32-Do-not-static-libgcc-link.patch              # This patch is only correct if using MSYS2's tcltk.
    - 0005-Win32-Extend-sqrt-NA_real_-hack-to-all-GCC-versions.patch
    - 0006-Win32-GCC-5.3-Fix-ISNAN-int-emits-UD2-insn.patch
    - 0007-Win32-MSYS2-ENV_CONV_EXCL_R_ARCH.patch
    - 0008-Darwin-set-DYLD_FALLBACK_LIBRARY_PATH.patch
    - 0009-R-3.3.0-Use-AC_SEARCH_LIBS-to-search-for-ncurses.patch
    - 0011-Linux-Do-not-modify-LD_LIBRARY_PATH.patch
    - 0012-macOS-include-cairo_h-not-cairo-xlib_h.patch
    - 0013-javareconf-do-not-fail-on-compile-fail.patch

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/
  no_link:
    # These files are modified by R CMD javareconf and can
    # point to different Java implementations in each env.
    - lib/R/etc/Makeconf
    - lib/R/etc/ldpaths
    - lib/R/etc/javaconf
    - lib/R/etc/x64/Makeconf
    - lib/R/etc/x64/ldpaths
    - lib/R/etc/x64/javaconf
  detect_binary_files_with_prefix: true
  # The current openblas-devel run exports
  # are overly restrictive IMHO, should be
  # open-ended.
  ignore_run_exports:
    - openblas-devel

requirements:
  build:
    - {{ compiler('c') }}                # [not win]
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('fortran') }}          # [not win]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libxrender') }}            # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libuuid') }}               # [linux]
    - {{ cdt('libsm-devel') }}           # [linux]
    - {{ cdt('libice-devel') }}          # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxt') }}                 # [linux]
    - {{ cdt('libxt-devel') }}           # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxau') }}                # [linux]
    - {{ cdt('java-1.7.0-openjdk') }}    # [linux]
    - {{posix}}pkg-config
    - posix                              # [win]
    - m2-texinfo-tex                     # [win]
    - m2-texinfo                         # [win]
    - m2-curl                            # [win]
    - m2-p7zip                           # [win]
    - texlive-core                       # [unix]
    - {{posix}}autoconf
    - {{posix}}automake-wrapper          # [win]
    - {{posix}}automake                  # [not win]
  host:
    - readline 6.2*            # [not win]
    - ncurses 5.9*             # [not win]
    - curl >=7.44.0,<8                     # [not win]
    - xz                                 # [not win]
    - libpng >=1.6.28,<1.7     # [not win]
    - {{native}}bzip2 1.0.*              # [not osx]
    - {{native}}libjpeg-turbo            # [win]
    - {{native}}toolchain                # [win]
    - {{native}}libiconv                 # [win]
    - {{native}}gmp 6.1.*            # [win]
    - {{native}}fftw                     # [win]
    - {{native}}xz                       # [win]
    - {{native}}mpfr 3.1.*           # [win]
    - {{native}}libsndfile               # [win]
    - {{native}}bwidget                  # [win]
    - {{native}}tktable                  # [win]
    - {{native}}libpng                   # [win]
    - {{native}}pango 1.40.*             # [not win]
    - {{native}}icu
    - {{native}}pcre
    - {{native}}tk                       # [win]
    - {{native}}tk 8.6.*                 # [not win]
    - zlib 1.2.11  # [not win]
    - {{native}}zlib 1.2.8
    - {{native}}zlib                     # [not win]
    - {{native}}gsl
    - {{native}}libtiff >=4.0.3,<4.0.8
    - {{native}}libxml2 2.9.*            # [win]
    - {{native}}libxml2                  # [not win]
    - {{native}}libssh2 1.*              # [not win]
    - {{native}}krb5 1.14.*              # [not win]
    - {{native}}openblas-devel >=0.2.20  # [linux]
    - {{native}}openblas                 # [win]

  run:
    - readline 6.2*            # [not win]
    - ncurses 5.9*             # [not win]
    - {{native}}gcc-libs                 # [win]
    - curl >=7.44.0,<8                     # [not win]
    - libpng >=1.6.28,<1.7     # [not win]
    - {{native}}bzip2 1.0.*              # [win]
    - {{native}}libjpeg-turbo            # [win]
    - {{native}}libiconv                 # [win]
    - {{native}}gmp 6.1.*            # [win]
    - {{native}}fftw                     # [win]
    - {{native}}xz                       # [win]
    - {{native}}mpfr 3.1.*           # [win]
    - {{native}}libsndfile               # [win]
    - {{native}}bwidget                  # [win]
    - {{native}}tktable                  # [win]
    - {{native}}libpng                   # [win]
    - {{native}}pango 1.*                # [not win]
    - {{native}}pcre
    - {{native}}tk                       # [win]
    - {{native}}tk 8.6.*                 # [not win]
    - zlib 1.2.11  # [not win]
    - {{native}}zlib 1.2.8
    - {{native}}gsl
    - {{native}}libtiff >=4.0.3,<4.0.8
    - {{native}}libtiff  # [win]
    - {{native}}libxml2 2.9.*            # [win]
    - {{native}}libssh2 1.*              # [not win]
    - {{native}}krb5 1.14.*              # [not win]
    - {{native}}libopenblas >=0.2.20     # [linux]
    - {{native}}openblas                 # [win]

test:
  commands:
    - R -h
    - R --version
    - Rscript --version
    - Rscript -e  'cat("ok\\n")'
    - open  # [win]
    # There doesn't seem to be a way to test this one
    # - RSetReg  # [win]
    - Rfe --help  # [win]
    - Rterm --help  # [win]
    - Rterm --version  # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.r-project.org/
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'R is a free software environment for statistical computing and graphics.'

extra:
  recipe-maintainers:
    - bgruening
    - johanneskoester
    - mingwandroid
    - ocefpaf
    - sodre
