travis:
  secure:
    BINSTAR_TOKEN: kctU26HfkXDme82SmylFidgcYJ56QJZRSQFHGsCp4/VHPSLI8kJnmOwL37YwGTC5EMM8AxBHM1tZsgoYT5xYUFd0vOMaER3NZ8g9cseKGvSLMnVqaY7Hj0hBdJOu2w+cYF0zCGfBfTmBJ8I04/pVLr7AszsVkHdP1MnLSU8pMsRhah+6pxpgF8y4frwnZjBz8mrLdoeiNjHs1g+xnnP+ASTXnzyIU+w2GgQBGxT8Wrd6OYZg2z5fISWxegw5tm8n0zxr+a0T4Ft3ydty8800qgeQUr8TfTpxuxuVcugwBOR9+vkfojv13VlnMYUuaiDJJr/Kq3405N3rUK/iDIj+tAIf9QnP2BWzdSBzLeU/6unNri3h2mgpCqU49JW5iVx/Mkk3oc1AeMyaWecoDK+kuEohHyJk18QZpUNc+QriFN+nqHKaJ+sojuUE6eQLPCer7OAg/w7tMhhbP5So7IwUskUz0h+uQ5RqsuQU0xMY6I1vxgqCNHGLm8iJpRsYfyfM8Gltyg4GIgeb7yGwB8lmXiQJQ5nGkwIjWoX2+2FHFoDaQqBYoZj+DnWv/NXlvpyEnzBZlljuDGrcNbsSfbpDouxlOLRdNU3DMR/MXVxx8tpsGFCvDKKkDaljchwhYS2402gFyIsjzdx2G7SHJYCnQ6lQD+2Dx2B5DvkxZh5Aqro=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
