travis:
  secure:
    BINSTAR_TOKEN: e3JynIdY21dyGTefHIiQbCYXFqEdcMxnLGeEE7qXcoSyatkqBhUbme2Ggy75p2QBCqttB9klt/Qv23CDD5Lt6Qf8S0p9qqjLX5P/X3oKt47MAsMjN9MvFl9rDbG9c1BG9TnBeGTpiZi39Y5J7VNKFATOmvJnvXcMS62mY05fc6nVCtt9V2kTXG6NspfgLlrFz+OoURt+JwDgtAU87FAQxS88bh4GPikHtcZ4ujOcuCooo+9LL4FAF+DXPgcwunrqg5VNQ+Q72crwlj+LxuyI0d0dJ0zxEL2UL6lphoZxLO1bv+dP8BOiHrUnD9vHmnIODlGdLD0nyONQpLjrMoeZa85iVCaJDHLfWWesBpUQz/lNlhW3bmXIIVEoZPLyjfYR4y2LM69WIpBIwc0KJlE9wpudvopKEijnUc7uPWb7thxKm8oNDfcM4S1kIvUojh5o8tQK2M9mXIh84YxDiAnyc0MnVTSfO4Vymsu1N92k15+izEeORtGQD6GEMWJBfZeVMhu56m6WFn/4JFtwrocj0MnFjOXVFFfKfuNFjYvyUUpw+UxNIrDG8Om8R4QWfhCR0b3an9aapkw5nzXsiYcR9+Q1xpyRI/jVw7IfcxHsgQHHAq4hs18SbXaJDFCUBEV6x+vwrFRtQRP60Viw2A129z5yHfqU/7iDLs2ZsiV7nfs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
