travis:
  secure:
    BINSTAR_TOKEN: TRowTbwqkbOmPBWCAl6/iD64wvf7AQQCd1yrGR4Y4hPKV0csHUyFHwGI2kZLLhS8SCWGr4SVVSmVtn6K4plx7npIpLoGtGZWIVJ77/7nI+xJtMd83xX3Ezm0ARYdxBCj5id4Bxx1BPG7enQOo+TTbmR3e1W+UpDoUvS1N1bz845U4IepNkeWh1Ytc20S64QgyyUrJvBfarGxezyhS8UVYSAlyZYJJBogQ3lomyKjAuzQxcUUPNPgGLh2/356ybqTOi61B6BCvV+P+1kTy5vCky/6xAaX1M+7gl+3xSQSj3PHAcov2EbwK/jQTx1c0XPfpvar9IV8N5JapfS2m99XbVuGg0YWPrDrYljvLp2f6GL8c8cYUnRQFc5XOlogvMTXqnP0ZGRO25E6uTCRz8mJ2/3LG48xfPBjwzbKqHtDyH/FnV5zzle31EEjvKqIaxdHItdEz9LzQnuj5yvSgnNr1m4db+XVOoc4DRw7LXhvxEfA73aqYv11YtxpwiknPWdhj+3o7t7balVz/GXk4Otuov2tbjUsa3rAvC+iEnVd/kX1qqjEfVzLK8D2McK/zSCgGhLz1V+xfW+Fle7yMHZkzS0sIGfZgt+nIUh/QcDYb6JSygy3WcH2832S61QzyiYcTiL9JXQF3wPcO+rPLmTwhJG8PAX35Nbnaf+Rts9r5s8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
