travis:
  secure:
    BINSTAR_TOKEN: YslNtFpF38VnbW8ChBN7gQf8fTe4R0CRB/F6gIhNFKqO97T4DyoDcIMYim4JEA8X0yxSA8WDQIrGlk6kUTTEea+KbH2xakAx+VWfYgwT1GN6yscGktMijrPuWfyBmAbPPqMDwRkZnU6ShFk0DNXALyym9dWoOqALOP0xNR+jIO6wXEWUyV+0WMi50a8mIyrBUmrnOx6PN42ztdvIAr2nl8Sb8ZAhkuOS7JCWtiNE+/iFkzKXrM9HrJe5GQJAKFZUCKUfLLtdXS5CYDFpqgjOkD5EEEDyDc1pao9u+WGVcnc9+rtHKVUmXo5SqpHhMXW1IQv8VpIRkOiTvCsmZzDO0Hiqn31+z604Kqu9lW63ljHrz1qykCRSURM0GOiuvqYR6l+woEEkMC6/sAyV1mrQFY05hilHmU6lVIU6j6YuItwL8HUcJVEYDgt/rMRVBjQx2RjP14W+Q64MmMjE8J7Vk5k9BBOwFXOg8kXbohWbzC/pCQxrR/PA3TAj5phPKA18koMOhTR2lUvEhsICRDc0Uv6mzXLfdiFU0V0cSN5kvUROPasQ/rgtC5EFI/tDMdr2qQMDQs5c67sZklEEmiIBV5Bf7J3kZ340GFHTG+mxiqY+PEr4aXLiMpi5olYmve92QeTMbBR43F2l7FRnQpBxEpavv0BPToO0qCgP+mBEgOg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
